Repository sseuda/sseuda, pull requests merged in 2025-06, with the labels that each got.

#34 Feat/signuppage
  sseuda-react/public/images/main/sseudaKorean.png
  sseuda-react/src/App.js
  sseuda-react/src/apis/MemberAPICalls.js
  sseuda-react/src/modules/MemberModule.js
  sseuda-react/src/pages/member/Login.js
  sseuda-react/src/pages/member/Signup.css
  sseuda-react/src/pages/member/Signup.js
Labels: feature✨

#37 Feat/logout
  sseuda-react/src/apis/MemberAPICalls.js
  sseuda-react/src/components/common/Header.js
  sseuda-react/src/modules/MemberModule.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/config/SecurityConfig.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/service/AuthService.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/jwt/JwtFilter.java
Labels: feature✨

#38 Feat/myblog
  sseuda-react/README.md
  sseuda-react/package-lock.json
  sseuda-react/package.json
  sseuda-react/src/App.js
  sseuda-react/src/apis/PostAPICalls.js
  sseuda-react/src/components/common/Global/Button.module.css
  sseuda-react/src/components/common/Global/MypageNavbar.module.css
  sseuda-react/src/components/common/MypageNavbar.js
  sseuda-react/src/components/common/post/BannerPost.js
  sseuda-react/src/components/common/post/MypagePost.js
  sseuda-react/src/components/common/post/TextEditor.js
  sseuda-react/src/components/common/post/css/MainBanner.module.css
  sseuda-react/src/components/common/post/css/MypagePost.module.css
  sseuda-react/src/components/common/post/css/PostTextEditor.module.css
  sseuda-react/src/layouts/MypageLayout.js
  sseuda-react/src/pages/Main.js
  sseuda-react/src/pages/Main.module.css
  sseuda-react/src/pages/myPage/MyPage.js
  sseuda-react/src/pages/myPage/css/MyPage.module.css
  sseuda-react/src/pages/post/PostBanner.js
  sseuda-react/src/pages/post/PostMypage.js
  sseuda-react/src/pages/post/PostTextEditor.js
  sseuda-react/src/pages/post/css/PostTextEditor.module.css
  sseuda-react/src/utils/tokenUtils.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/dao/MemberMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/controller/PostController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/dao/PostMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/service/PostService.java
  sseuda_server/src/main/resources/mapper/MemberMapper.xml
  sseuda_server/src/main/resources/mapper/PostMapper.xml
Labels: feature✨

#39 feat: 로그아웃 수정
  sseuda-react/src/apis/MemberAPICalls.js
  sseuda-react/src/components/common/Header.js
Labels: feature✨

#40 Feat/mainpage
  sseuda-react/src/pages/Main.js
  sseuda-react/src/pages/Main.module.css
Labels: feature✨

#42 Feat/myblog
  sseuda-react/src/App.js
  sseuda-react/src/apis/PostAPICalls.js
  sseuda-react/src/components/common/post/MainPost.js
  sseuda-react/src/components/common/post/TextEditor.js
  sseuda-react/src/components/common/post/css/PostTextEditor.module.css
  sseuda-react/src/pages/post/PostDetail.js
  sseuda-react/src/pages/post/PostMypage.js
  sseuda-react/src/pages/post/UserPage.js
  sseuda_server/.gitignore
  sseuda_server/src/main/java/com/sseuda/sseuda_server/config/SecurityConfig.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/config/WebConfig.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/service/MemberService.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/controller/PostController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/dao/PostMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/dto/PostDTO.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/service/PostService.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/util/FileUploadUtils.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/util/ImageUploadController.java
  sseuda_server/src/main/resources/mapper/PostMapper.xml
  sseuda_server/uploads/1749437620105.png
  sseuda_server/uploads/1749437728392.png
  sseuda_server/uploads/1749437930902.png
  sseuda_server/uploads/1749437941147.png
Labels: feature✨

#44 feat: 알람 조회(사용자별)
  sseuda_server/src/main/java/com/sseuda/sseuda_server/config/SecurityConfig.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/controller/AlarmController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/dao/AlarmMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/dto/AlarmDTO.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/service/AlarmService.java
  sseuda_server/src/main/resources/mapper/AlarmMapper.xml
  sseuda_server/src/main/resources/sql/sseuda_build_script.sql
Labels: feature✨

#45 Feat/myblog
  sseuda-react/src/components/common/Global/Footer.module.css
  sseuda-react/src/components/common/category/CategoryNav.js
  sseuda-react/src/components/common/post/MainPost.js
  sseuda-react/src/components/common/post/TextEditor.js
  sseuda-react/src/components/common/post/css/PostTextEditor.module.css
  sseuda-react/src/layouts/PostLayout.js
  sseuda-react/src/pages/post/PostMypage.js
  sseuda-react/src/pages/post/UserPage.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/controller/PostController.java
  sseuda_server/src/main/resources/mapper/PostMapper.xml
Labels: bug🐞, feature✨

#46 Feat/post
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/controller/PostController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/dao/PostMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/service/PostService.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/jwt/JwtFilter.java
  sseuda_server/src/main/resources/mapper/PostMapper.xml
Labels: feature✨

#48 feat: 사용자 권한 변경
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/controller/MemberController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/dao/MemberMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/dto/UserRoleDTO.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/service/MemberService.java
  sseuda_server/src/main/resources/mapper/MemberMapper.xml
Labels: feature✨

#49 Feat/comment
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/controller/CommentController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/dao/CommentMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/dto/CommentDTO.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/service/CommentService.java
  sseuda_server/src/main/resources/mapper/CommentMapper.xml
Labels: feature✨

#51 Feat/mypage
  sseuda-react/src/apis/CommentAPICalls.js
  sseuda-react/src/components/common/comment/Comment.js
  sseuda-react/src/components/common/comment/CommentUpdate.js
  sseuda-react/src/pages/comment/PostComment.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/controller/CommentController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/dao/CommentMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/service/CommentService.java
  sseuda_server/src/main/resources/mapper/CommentMapper.xml
Labels: feature✨

#55 Feat/admin page
  sseuda-react/src/App.js
  sseuda-react/src/apis/MemberAPICalls.js
  sseuda-react/src/apis/ReportsAPICalls.js
  sseuda-react/src/apis/UserRoleAPICalls.js
  sseuda-react/src/components/common/AdminPageNavbar.js
  sseuda-react/src/components/common/Header.js
  sseuda-react/src/layouts/AdminPageLayout.js
  sseuda-react/src/modules/MemberModule.js
  sseuda-react/src/modules/ReportsModule.js
  sseuda-react/src/modules/UserRoleModule.js
  sseuda-react/src/modules/index.js
  sseuda-react/src/pages/admin/AdminPage.css
  sseuda-react/src/pages/admin/AdminPage.js
  sseuda-react/src/pages/admin/AdminReports.css
  sseuda-react/src/pages/admin/AdminReports.js
  sseuda-react/src/pages/admin/SuperAdminPage.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/config/SecurityConfig.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/UserStatus.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/controller/MemberController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/dao/MemberMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/member/service/MemberService.java
  sseuda_server/src/main/resources/mapper/MemberMapper.xml
  sseuda_server/src/main/resources/mapper/ReportsMapper.xml
  sseuda_server/src/main/resources/sql/sseuda_build_script.sql
Labels: feature✨

#59 Feat/myblog
  sseuda-react/src/apis/PostAPICalls.js
  sseuda-react/src/components/common/post/ViewCount.js
  sseuda-react/src/modules/PostModule.js
  sseuda-react/src/pages/post/PostDetail.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/config/SecurityConfig.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/controller/PostController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/dao/PostMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/service/PostService.java
  sseuda_server/src/main/resources/mapper/PostMapper.xml
Labels: feature✨

#62 Feat/mypage
  sseuda-react/src/App.js
  sseuda-react/src/apis/MemberAPICalls.js
  sseuda-react/src/components/common/Global/Button.module.css
  sseuda-react/src/components/common/Global/Pagination.module.css
  sseuda-react/src/components/common/MypageNavbar.js
  sseuda-react/src/components/common/post/MainPost.js
  sseuda-react/src/components/common/post/MypagePost.js
  sseuda-react/src/components/common/post/TextEditor.js
  sseuda-react/src/components/common/post/TextEditorUpdate.js
  sseuda-react/src/components/common/post/css/MainPost.module.css
  sseuda-react/src/components/member/UesrBlog.js
  sseuda-react/src/components/member/UserInfo.js
  sseuda-react/src/components/member/css/UserInfo.module.css
  sseuda-react/src/modules/PostModule.js
  sseuda-react/src/pages/Main.js
  sseuda-react/src/pages/myPage/MyInformation.js
  sseuda-react/src/pages/myPage/css/MyPage.module.css
  sseuda-react/src/pages/post/PostMain.js
  sseuda-react/src/pages/post/PostMypage.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/controller/PostController.java
Labels: bug🐞, feature✨

#63 Feat/mypage
  sseuda-react/src/pages/post/PostMain.js
Labels: bug🐞

#65 fix: 조회수 증가
  sseuda-react/src/components/common/post/MainPost.js
  sseuda-react/src/components/common/post/MypagePost.js
Labels: bug🐞

#67 Feat/likes
  sseuda-react/src/components/common/post/css/PostTextEditor.css
  sseuda-react/src/components/common/post/css/PostTextEditor.module.css
  sseuda-react/src/pages/post/PostMypage.js
  sseuda-react/src/pages/post/UserPage.js
  sseuda-react/src/pages/post/css/PostDetail.module.css
  sseuda_server/src/main/java/com/sseuda/sseuda_server/config/SecurityConfig.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/likes/controller/LikesController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/likes/dao/LikesMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/likes/dto/LikesDTO.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/likes/service/LikesService.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/post/controller/PostController.java
  sseuda_server/src/main/resources/mapper/LikesMapper.xml
Labels: feature✨

#68 Feat/alarm
  sseuda-react/src/apis/CommentAPICalls.js
  sseuda-react/src/components/common/comment/CommentInsert.js
  sseuda-react/src/pages/alarm/Alarm.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/controller/AlarmController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/dao/AlarmMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/dto/AlarmDTO.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/service/AlarmService.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/controller/CommentController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/dao/CommentMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/comment/service/CommentService.java
  sseuda_server/src/main/resources/mapper/AlarmMapper.xml
  sseuda_server/src/main/resources/mapper/CommentMapper.xml
  sseuda_server/src/main/resources/sql/sseuda_build_script.sql
Labels: bug🐞, feature✨

#70 Feat/alarm
  sseuda-react/src/apis/AlarmAPICalls.js
  sseuda-react/src/modules/AlarmModule.js
  sseuda-react/src/pages/alarm/Alarm.css
  sseuda-react/src/pages/alarm/Alarm.js
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/alarm/controller/AlarmController.java
Labels: feature✨

#71 Feat/alarm
  sseuda-react/src/components/common/Global/Header.module.css
  sseuda-react/src/components/common/Header.js
  sseuda-react/src/pages/alarm/Alarm.css
  sseuda-react/src/pages/alarm/Alarm.js
Labels: feature✨

#72 Feat/alarm
  sseuda-react/src/components/common/Global/Header.module.css
  sseuda-react/src/components/common/Header.js
  sseuda-react/src/pages/alarm/Alarm.css
  sseuda-react/src/pages/alarm/Alarm.js
  sseuda-react/src/pages/alarm/Alarm.module.css
  sseuda_server/src/main/resources/mapper/AlarmMapper.xml
Labels: feature✨, refactor♻️

#75 feat: SuperAdminPage는 SUPER권한만 접속 가능
  sseuda-react/src/App.js
  sseuda-react/src/components/common/auth/SuperRoute.js
Labels: feature✨

#76 css: header
  sseuda-react/src/components/common/Global/Header.module.css
  sseuda-react/src/components/common/Header.js
Labels: css🎨

#80 Feat/myblog
  sseuda-react/src/App.js
  sseuda-react/src/apis/LikesAPICalls.js
  sseuda-react/src/apis/PostAPICalls.js
  sseuda-react/src/components/common/likes/LikesFolder.js
  sseuda-react/src/components/common/likes/LikesSave.js
  sseuda-react/src/components/common/post/BannerPost.js
  sseuda-react/src/components/common/post/MypagePost.js
  sseuda-react/src/components/common/post/TextEditor.js
  sseuda-react/src/components/common/post/UserLikesList.js
  sseuda-react/src/components/common/post/css/MypagePost.module.css
  sseuda-react/src/modules/LikesModule.js
  sseuda-react/src/pages/likes/LikesList.js
  sseuda-react/src/pages/myPage/MyPage.js
  sseuda-react/src/pages/post/PostDetail.js
  sseuda-react/src/pages/post/PostMypage.js
  sseuda-react/src/pages/post/css/SwiperSlide.css
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/likes/controller/LikesController.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/likes/dao/LikesMapper.java
  sseuda_server/src/main/java/com/sseuda/sseuda_server/function/likes/service/LikesService.java
  sseuda_server/src/main/resources/mapper/LikesMapper.xml
Labels: bug🐞, feature✨, refactor♻️, css🎨
